DDD: DED Namespace Reference
DED Namespace Reference
Functions
size_t peak ()
void garbage ()
GDDD add (const std::set< GDDD > &s)
GDDD add (const d3::set< GDDD >::type &)
unsigned int statistics ()
void pstats (bool reinit=true)
Function Documentation
GDDD DED::add (const d3::set< GDDD >::type &)
GDDD DED::add (const std::set< GDDD > & s)
References GDDD::begin(), _DED_Add::create(), and GDDD::null.
Referenced by _DED_Add::eval(), Apply2k::eval(), DomExtract::eval(), StrongHom::eval(), Add::eval(), sns::RecFireSat::eval(), Fixpoint::eval(), MLHomAdapter::eval(), sns::Fixpoint::eval(), fixpoint(), Fixpoint::has_image(), sns::Fixpoint::has_image(), and operator+().
void DED::garbage ()
References DEDpeak, namespace_SDED::Max_SDED, UniqueTable< T >::size(), and UniqueTable< T >::table.
Referenced by MemoryManager::garbage().
size_t DED::peak ()
References DEDpeak, namespace_SDED::Max_SDED, UniqueTable< T >::size(), and UniqueTable< T >::table.
Referenced by Statistic::load().
void DED::pstats (bool reinit = true)
References cache, Hits, Misses, and UniqueTable< T >::size().
Referenced by MemoryManager::pstats().
unsigned int DED::statistics ()
References UniqueTable< T >::table.
Referenced by Statistic::load(), MemoryManager::nbDED(), and SDED::pstats().
Please comment this page and report errors about it on the RefDocComments page.